# Generated by Django 2.0.1 on 2018-03-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180328_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, to='mainpage.Product'),
        ),
    ]
